name: Calculator Unit Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .Net environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'
        
    - name: Install Test Platform
      working-directory: /home/runner/work/CICalculatorTest/CICalculatorTest/Calculator
      run: dotnet add package Microsoft.TestPlatform --version 17.5.0

    - name: Dependency Restore
      run: dotnet restore

    - name: Project Build
      run: dotnet build

    - name: Project Test
      run: dotnet test
